spring.application.name=SpringSecurityDemo


#spring.security.user.name=faiz
#spring.security.user.password="12345"

spring.datasource.url=jdbc:mysql://localhost:3306/curd_springboot
spring.datasource.username=root
spring.datasource.password=7276&;;fzad


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

// Normal generated for practice purpose
jwt.secret=x2fk3F7urle1SvHa725OMJqIXUdY8MDi4PF1T5Wy3J0=
jwt.issuer=fzad-api
jwt.expiry=900