spring.application.name=SpringProfileDemo

server.port=8080

app.welcome.message=LOCAL : Hello welcome to my application

app.welcome.code=200
app.welcome.users=faiz, rohan, rehan

#We can set this with terminal or environment variable
#spring.profiles.active= prod