spring.application.name=CurdSpringBootDemo

spring.datasource.url=jdbc:mysql://localhost:3306/curd_springboot
spring.datasource.username=root
spring.datasource.password=7276&;;fzad

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true